# Dockerfile
FROM php:7.4.33

WORKDIR /adminoid-site

# it's good
RUN ls -la > /adminoid-site/temp_run_ls1.txt
RUN ls > /adminoid-site/temp_run_ls2.txt

EXPOSE 8080

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3051

CMD ls -la > /matrix-bnb-web/temp_cmd_lsla.txt
