version: "3.8"

services:

#  caddy:
#    image: lucaslorentz/caddy-docker-proxy:ci-alpine
#    ports:
#      - 80:80
#      - 443:443
#    environment:
#      - CADDY_INGRESS_NETWORKS=caddy
#    networks:
#      - caddy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - caddy_data:/data
#    restart: unless-stopped

#  matrix_bnb_web:
#    tty: true
#    stdin_open: true
#    build: ./matrix_bnb_web
#    command: tail -f /dev/null
#    networks:
#      - caddy
#    volumes:
#      - /var/web/matrix-bnb-web:/matrix-bnb-web
#    ports:
#      - "3051:3051"
#    labels:
#      caddy: angryhacker.ru www.angryhacker.ru
#      caddy.reverse_proxy: "{{upstreams 3051}}"

  laravel_adminoid:
#    network_mode: host
    build:
      context: ..
      dockerfile: .docker/laravel_adminoid/Dockerfile
    tty: true
    stdin_open: true
#    command: php artisan serve --host=0.0.0.0 --port=8000
    restart: unless-stopped
    volumes:
      - site_adminoid:/adminoid_site
    networks:
      - adminoid
      - caddy
    ports:
      - "8000:8000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD_ROOT}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - adminoid

networks:
  caddy:
  adminoid:
    driver: bridge

volumes:
  caddy_data: {}
  mariadb_data: {}
  site_adminoid: {}

