version: "3.8"

services:

#  caddy:
#    image: lucaslorentz/caddy-docker-proxy:ci-alpine
#    ports:
#      - 80:80
#      - 443:443
#    environment:
#      - CADDY_INGRESS_NETWORKS=caddy
#    networks:
#      - caddy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - caddy_data:/data
#    restart: unless-stopped

#  matrix_bnb_web:
#    tty: true
#    stdin_open: true
#    build: ./matrix_bnb_web
#    command: tail -f /dev/null
#    networks:
#      - caddy
#    volumes:
#      - /var/web/matrix-bnb-web:/matrix-bnb-web
#    ports:
#      - "3051:3051"
#    labels:
#      caddy: angryhacker.ru www.angryhacker.ru
#      caddy.reverse_proxy: "{{upstreams 3051}}"

  laravel_adminoid:
#    network_mode: host
    build:
      context: ..
      dockerfile: .docker/laravel_adminoid/Dockerfile
    tty: true
    stdin_open: true
#    command: php artisan serve
    restart: unless-stopped
    networks:
      - adminoid
      - caddy
    ports:
      - "8000:8000"

networks:
  caddy:
  adminoid:
    driver: bridge
#    driver_opts:
#      enable_ipv4: 1
#      enable_ipv6: 1
#    external: true

volumes:
  caddy_data: {}

